annotations:
  artifacthub.io/images: |
    - name: gotify
      image: gotify/server:2.6.3
      platforms:
        - linux/amd64
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/pmoscode-helm/gotify
    - name: support
      url: https://github.com/pmoscode-helm/gotify/issues
  artifacthub.io/maintainers: |
    - name: pmoscode
      email: info@pmoscode.de
  artifacthub.io/cr.source: "gotify/server"
  artifacthub.io/own.source: "gotify_server"
  artifacthub.io/cr.update-strategy: "latest"
apiVersion: v2
appVersion: 2.7.3
description: Gotify - a simple server for sending and receiving messages
home: https://gotify.net/
icon: https://github.com/gotify/logo/raw/master/gotify-logo-small.png
maintainers:
- email: info@pmoscode.de
  name: pmoscode
  url: https://pmoscode.de
name: gotify
sources:
- https://gotify.net/
type: application
version: 0.5.2
