annotations:
  artifacthub.io/cr.source: infiniflow/ragflow
  artifacthub.io/cr.update-strategy: github
  artifacthub.io/github.source: https://api.github.com/repos/infiniflow/ragflow/releases/latest
  artifacthub.io/own.source: ragflow
apiVersion: v2
appVersion: 0.21.1
description: A Helm chart for deploying RAGFlow on Kubernetes
name: ragflow
type: application
version: 0.1.0
