apiVersion: v2
name: farfalle
description: A Helm chart for Farfalle AI-powered search engine
type: application
version: 0.1.0
appVersion: latest
annotations:
  artifacthub.io/cr.source: "notgard/farfalle"
  artifacthub.io/own.source: "farfalle"
  artifacthub.io/cr.update-strategy: "no"