# Default values for farfalle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Default storage size
storageSize: 20Gi
storageClass: "alicloud-disk-essd"

# Database configuration
database:
  enabled: true
  name: postgres
  user: postgres
  password: password
  image: postgresql:15.3.0-debian-11-r7

# Redis configuration
redis:
  enabled: false

# Searxng configuration
searxng:
  enabled: true
  image: searxng/searxng:latest

# Standalone configuration (frontend and backend in one)
standalone:
  image: notgard/farfalle
  tag: latest
  backendPort: 8000
  frontendPort: 3000

# Kubectl image for IP update job
kubectl:
  image: bitnami/kubectl:latest

# Service configuration
service:
  type: LoadBalancer

externalEnv:
  model:
    OPENAI_API_KEY: ""

resources: {}