apiVersion: v2
name: tolgee
description: A Helm chart for Tolgee localization platform
type: application
version: 0.1.0
appVersion: 3.138.0
annotations:
  artifacthub.io/cr.source: "tolgee/tolgee"
  artifacthub.io/own.source: "tolgee"
  artifacthub.io/cr.update-strategy: "latest"