annotations:
  artifacthub.io/cr.source: tolgee/tolgee
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: tolgee
apiVersion: v2
appVersion: v3.141.1
description: A Helm chart for Tolgee localization platform
name: tolgee
type: application
version: 0.1.0
