apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dify.fullname" . }}-api
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  serviceName: {{ include "dify.fullname" . }}-api
  replicas: 1
  selector:
    matchLabels:
      {{- include "dify.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "dify.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: MODE
              value: "api"
            - name: DB_USERNAME
              value: {{ .Values.externalEnv.postgresql.env.DB_USERNAME | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.externalEnv.postgresql.env.DB_PASSWORD | quote }}
            {{- if .Values.externalEnv.postgresql.enabled  | default true }}
            - name: DB_HOST
              value: {{ include "dify.fullname" . }}-postgresql
            {{- else }}
            - name: DB_HOST
              value: {{ .Values.externalEnv.postgresql.env.DB_HOST | quote }}
            {{- end }}
            - name: DB_PORT
              value: {{ .Values.externalEnv.postgresql.env.DB_PORT | quote }}
            - name: DB_DATABASE
              value: {{ .Values.externalEnv.postgresql.env.DB_DATABASE | quote }}
            {{- if .Values.externalEnv.redis.enabled | default true }}
            - name: REDIS_HOST
              value: "{{ include "dify.fullname" . }}-redis-master"
            {{- else }}
            - name: REDIS_HOST
              value: {{ .Values.externalEnv.redis.env.REDIS_HOST | quote}}
            {{- end }}
            - name: REDIS_PORT
              value: {{ .Values.externalEnv.redis.env.REDIS_PORT | quote}}
            - name: REDIS_PASSWORD
              value: {{ .Values.externalEnv.redis.env.REDIS_PASSWORD | quote}}
            - name: REDIS_DB
              value: {{ .Values.externalEnv.redis.env.REDIS_DB | quote}}
            - name: CELERY_BROKER_URL
              value: "redis://:{{ .Values.externalEnv.redis.env.REDIS_PASSWORD }}@{{ .Values.externalEnv.redis.env.REDIS_HOST }}:{{ .Values.externalEnv.redis.env.REDIS_PORT }}/1"
            - name: WEAVIATE_ENDPOINT
              value: "http://{{ include "dify.fullname" . }}-weaviate:{{ .Values.weaviate.service.port }}"
            - name: WEAVIATE_API_KEY
              value: "WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih"
            - name: SANDBOX_API_KEY
              value: "dify-sandbox"
            - name: PLUGIN_DIFY_INNER_API_KEY
              value: "QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1"
            - name: PLUGIN_DIFY_INNER_API_URL
              value: "http://{{ include "dify.fullname" . }}-api:5001"
            - name: PLUGIN_DAEMON_URL
              value: "http://{{ include "dify.fullname" . }}-plugin-daemon:5002"
            - name: PLUGIN_DAEMON_KEY
              value: "lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi"
            - name: STORAGE_TYPE
              value: "opendal"
            - name: OPENDAL_SCHEME
              value: "fs"
            - name: OPENDAL_FS_ROOT
              value: "/app/api/storage"
            - name: SECRET_KEY
              value: ""
            - name: MIGRATION_ENABLED
              value: "true"
            - name: VECTOR_STORE
              value: "weaviate"
            - name: ENABLED_PLUGINS
              value: "all"
            - name: PLUGIN_INIT_TIMEOUT
              value: "600"
            - name: GEVENT_ENABLE
              value: "true"
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          volumeMounts:
            - name: storage
              mountPath: /app/api/storage
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "dify.fullname" . }}-api-storage
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}