{{- if .Values.externalEnv.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dify.fullname" . }}-redis-master
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dify.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "dify.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          env:
            - name: REDISCLI_AUTH
              value: {{ .Values.externalEnv.redis.env.REDIS_PASSWORD | quote }}
          ports:
            - name: redis
              containerPort: {{ .Values.externalEnv.redis.env.REDIS_PORT }}
              protocol: TCP
          command:
            - "redis-server"
            - "--requirepass"
            - {{ .Values.externalEnv.redis.env.REDIS_PASSWORD | quote }}
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.redis.master.resources | nindent 12 }}
      volumes:
        - name: data
          emptyDir: {}
      {{- with .Values.redis.master.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.master.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.master.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}