{{- if .Values.externalEnv.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-redis-master
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.externalEnv.redis.env.REDIS_PORT | default 6379 }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}