apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dify.fullname" . }}-worker
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dify.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "dify.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          env:
            - name: MODE
              value: "worker"
            - name: DB_USERNAME
              value: {{ .Values.externalEnv.postgresql.env.DB_USERNAME | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.externalEnv.postgresql.env.DB_PASSWORD | quote }}
            {{- if .Values.externalEnv.postgresql.enabled | default true }}
            - name: DB_HOST
              value: {{ include "dify.fullname" . }}-postgresql
            {{- else }}
            - name: DB_HOST
              value: {{ .Values.externalEnv.postgresql.env.DB_HOST | quote }}
            {{- end }}
            - name: DB_PORT
              value: {{ .Values.externalEnv.postgresql.env.DB_PORT | quote }}
            - name: DB_DATABASE
              value: {{ .Values.externalEnv.postgresql.env.DB_DATABASE | quote }}
            {{- if .Values.externalEnv.redis.enabled | default true }}
            - name: REDIS_HOST
              value: "{{ include "dify.fullname" . }}-redis-master"
            {{- else }}
            - name: REDIS_HOST
              value: {{ .Values.externalEnv.redis.env.REDIS_HOST | quote}}
            {{- end }}
            - name: REDIS_PORT
              value: {{ .Values.externalEnv.redis.env.REDIS_PORT | quote}}
            - name: REDIS_PASSWORD
              value: {{ .Values.externalEnv.redis.env.REDIS_PASSWORD | quote}}
            - name: REDIS_DB
              value: {{ .Values.externalEnv.redis.env.REDIS_DB | quote}}
            - name: CELERY_BROKER_URL
              value: "redis://:{{ .Values.externalEnv.redis.env.REDIS_PASSWORD }}@{{ .Values.externalEnv.redis.env.REDIS_HOST }}:{{ .Values.externalEnv.redis.env.REDIS_PORT }}/1"
            - name: WEAVIATE_ENDPOINT
              value: "http://{{ include "dify.fullname" . }}-weaviate:{{ .Values.weaviate.service.port }}"
            - name: WEAVIATE_API_KEY
              value: "WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih"
            - name: SANDBOX_API_KEY
              value: "dify-sandbox"
            - name: PLUGIN_DIFY_INNER_API_KEY
              value: "QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1"
            - name: STORAGE_TYPE
              value: "opendal"
            - name: OPENDAL_SCHEME
              value: "fs"
            - name: OPENDAL_FS_ROOT
              value: "/app/api/storage"
            - name: SECRET_KEY
              value: ""
            - name: MIGRATION_ENABLED
              value: "true"
            - name: GEVENT_ENABLE
              value: "true"
          volumeMounts:
            - name: storage
              mountPath: /app/api/storage
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      volumes:
        - name: storage
          emptyDir: {}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}