{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) (eq .Values.persistence.config.type "pvc") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nzbget.fullname" . }}-config
  labels:
    {{- include "nzbget.labels" . | nindent 4 }}
  {{- with .Values.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
  {{- if .Values.persistence.config.storageClass }}
  {{- if (eq "-" .Values.persistence.config.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.config.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
---
{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) (eq .Values.persistence.media.type "pvc") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nzbget.fullname" . }}-media
  labels:
    {{- include "nzbget.labels" . | nindent 4 }}
  {{- with .Values.persistence.media.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.media.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size | quote }}
  {{- if .Values.persistence.media.storageClass }}
  {{- if (eq "-" .Values.persistence.media.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.media.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
---
{{- if and .Values.persistence.downloads.enabled (not .Values.persistence.downloads.existingClaim) (eq .Values.persistence.downloads.type "pvc") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nzbget.fullname" . }}-downloads
  labels:
    {{- include "nzbget.labels" . | nindent 4 }}
  {{- with .Values.persistence.downloads.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.downloads.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.downloads.size | quote }}
  {{- if .Values.persistence.downloads.storageClass }}
  {{- if (eq "-" .Values.persistence.downloads.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.downloads.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}