annotations:
  artifacthub.io/changes: "- kind: changed\n  description: Upgraded `common` chart\
    \ dependency to version 4.5.2"
  artifacthub.io/cr.source: linuxserver/bazarr
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: linuxserver_bazarr
apiVersion: v2
appVersion: v1.5.3-ls324
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
description: Bazarr is a companion application to Sonarr and Radarr. It manages and
  downloads subtitles based on your requirements
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/bazarr
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr.png
keywords:
- bazarr
- radarr
- sonarr
- subtitles
- usenet
- torrent
kubeVersion: '>=1.16.0-0'
maintainers:
- email: jeff@billimek.com
  name: billimek
name: bazarr
sources:
- https://github.com/morpheus65535/bazarr
- https://github.com/k8s-at-home/container-images
version: 10.6.2
