apiVersion: v2
name: umami
version: 1.0.0
description: A Helm chart for deploying Umami on Kubernetes
appVersion: postgresql-latest
annotations:
  artifacthub.io/cr.source: "umamisoftware/umami"
  artifacthub.io/own.source: "umami"
  artifacthub.io/cr.update-strategy: "no"