replicaCount: 1
image:
  repository: app.image
  tag: 
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 3000
env:
  DATABASE_URL: "postgresql://admin:umami@postgresql/umami"
resources:
  {}
persistence:
  enabled: false
  size:  20Gi
  storageClassName: ""
postgresql:
  enabled: true
  image:
    repository: postgresql.image
    tag: postgresql.image.tag
    pullPolicy: IfNotPresent
  port: 5432
  user: admin
  password: umami
  db: umami
  persistence:
    enabled: true
    size:  20Gi
    storageClassName: ""