apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cusdis.fullname" . }}
  labels:
    {{- include "cusdis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cusdis.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cusdis.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NEXTAUTH_URL
              value: {{ .Values.env.NEXTAUTH_URL | quote }}
            - name: DB_TYPE
              value: {{ .Values.env.DB_TYPE | quote }}
            - name: DB_URL
              value: {{ .Values.env.DB_URL | quote }}
            - name: USERNAME
              value: {{ .Values.env.USERNAME | quote }}
            - name: JWT_SECRET
              value: {{ .Values.env.JWT_SECRET | quote }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cusdis.fullname" . }}-secret
                  key: password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}