{{- if .Values.mindsdb.apiKeys.googleApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mindsdb.fullname" . }}-api-keys
  labels:
    {{- include "mindsdb.labels" . | nindent 4 }}
type: Opaque
data:
  google-api-key: {{ .Values.mindsdb.apiKeys.googleApiKey | b64enc | quote }}
{{- end }}