apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mindsdb.fullname" . }}-config
  labels:
    {{- include "mindsdb.labels" . | nindent 4 }}
data:
  MINDSDB_DB_CON: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "mindsdb.fullname" . }}-postgresql/{{ .Values.postgresql.auth.database }}"
  MINDSDB_DOCKER_ENV: "True"
  MINDSDB_STORAGE_DIR: "/mindsdb/var"
  FLASK_DEBUG: "1"
  # 其他可能需要的环境变量
  MINDSDB_CONFIG_FILE: "/mindsdb/var/config.json"