{{- if .Values.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mindsdb.fullname" . }}-postgresql-pvc
  labels:
    {{- include "mindsdb.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode | default "ReadWriteOnce" | quote }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | quote }}
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass | quote }}
  {{- else if .Values.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
  {{- end }}
{{- end }}