apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mindsdb.fullname" . }}-postgres-secret
  labels:
    {{- include "mindsdb.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}