apiVersion: v2
appVersion: 7.2.3
annotations:
  artifacthub.io/cr.source: "unleashorg/unleash-server"
  artifacthub.io/own.source: "unleashorg_unleash-server"
  artifacthub.io/cr.update-strategy: "latest"
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 13.4.4
description: Unleash is a open source feature flag & toggle system, that gives you
  a great overview over all feature toggles across all your applications and services.
icon: https://docs.getunleash.io/img/logo.svg
maintainers:
- name: evanstucker-hates-2fa
- email: ivarconr@gmail.com
  name: ivarconr
name: unleash
sources:
- https://github.com/Unleash/unleash
- https://github.com/Unleash/helm-charts
type: application
version: 5.6.2
