apiVersion: v2
appVersion: 2.0.2
annotations:
  artifacthub.io/cr.source: "louislam/uptime-kuma"
  artifacthub.io/own.source: "louislam_uptime-kuma"
  artifacthub.io/github.source: "https://api.github.com/repos/louislam/uptime-kuma/releases/latest"
  artifacthub.io/cr.update-strategy: "github"
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 20.2.2
description: A self-hosted Monitoring tool like "Uptime-Robot".
home: https://github.com/dirsigler/uptime-kuma-helm
icon: https://raw.githubusercontent.com/louislam/uptime-kuma/master/public/icon.png
maintainers:
- email: dennis@irsigler.dev
  name: dirsigler
name: uptimekuma
sources:
- https://github.com/louislam/uptime-kuma
type: application
version: 2.21.3
