{{- if and .Values.config.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jellyseerr.configPersistenceName" . }}
  labels:
    {{- include "jellyseerr.labels" . | nindent 4 }}
  {{- with .Values.config.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.config.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.config.persistence.size | quote }}
  {{- with .Values.config.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .Values.config.persistence.volumeName }}
  volumeName: {{ . }}
  {{- end }}
{{- end }}