annotations:
  artifacthub.io/cr.source: linuxserver/code-server
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: code-server
apiVersion: v2
appVersion: 4.106.3-ls307
description: A Helm chart for coder/code-server
name: code-server
type: application
version: 3.31.2
