annotations:
  artifacthub.io/cr.source: langgenius/dify-api
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: dify-api
apiVersion: v2
appVersion: 1.9.2
description: A Helm chart for Dify AI application
name: dify
type: application
version: 0.1.0
