apiVersion: v2
name: dify
description: A Helm chart for Dify AI application
type: application
version: 0.1.0
appVersion: 1.8.1
annotations:
  artifacthub.io/cr.source: "langgenius/dify-api"
  artifacthub.io/own.source: "dify-api"
  artifacthub.io/cr.update-strategy: "latest"