kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "local-ai.fullname" .) "models" }}
  labels:
    {{- include "local-ai.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.models.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.models.size | quote }}
  {{- if .Values.persistence.models.storageClass }}
  storageClassName: {{ .Values.persistence.models.storageClass | quote }}
  {{- end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "local-ai.fullname" .) "output" }}
  labels:
    {{- include "local-ai.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.output.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.output.size | quote }}
  {{- if .Values.persistence.output.storageClass }}
  storageClassName: {{ .Values.persistence.output.storageClass | quote }}
  {{- end }}