apiVersion: v2
name: langflow
description: A Helm chart for Langflow
type: application
version: 0.1.0
appVersion: 1.6.5
annotations:
  artifacthub.io/cr.source: "langflowai/langflow-frontend"
  artifacthub.io/own.source: "langflow-frontend"
  artifacthub.io/cr.update-strategy: "latest"