{{- if .Values.persistence.plugins.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "etherpad-lite.fullname" . }}-plugins
  labels:
    {{- include "etherpad-lite.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.plugins.accessModes | nindent 4 }}
  storageClassName: {{ .Values.persistence.plugins.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.plugins.size }}
{{- end }}
---
{{- if .Values.persistence.var.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "etherpad-lite.fullname" . }}-var
  labels:
    {{- include "etherpad-lite.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.var.accessModes | nindent 4 }}
  storageClassName: {{ .Values.persistence.var.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.var.size }}
{{- end }}
