apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etherpad-lite.fullname" . }}-secret
  labels:
    {{- include "etherpad-lite.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_PASSWORD: {{ .Values.etherpad.adminPassword | quote }}
  DB_USER: {{ .Values.postgresql.auth.username | quote }}
  DB_PASS: {{ .Values.postgresql.auth.password | quote }}
  DB_NAME: {{ .Values.postgresql.auth.database | quote }}
