apiVersion: v1
kind: Service
metadata:
  name: {{ include "etherpad.fullname" . }}
  labels:
    {{- include "etherpad.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9001
      protocol: TCP
      name: http
  selector:
    {{- include "etherpad.selectorLabels" . | nindent 4 }}