image:
  repository: djyde/cusdis
  tag:
  pullPolicy: IfNotPresent
  kubectl: kubectl.image

service:
  type: LoadBalancer
  port: 3000

env:
  NEXTAUTH_URL: http://localhost:3000
  DB_TYPE: sqlite
  DB_URL: file:/data/db.sqlite
  USERNAME: admin
  JWT_SECRET: your_jwt_secret

secret:
  PASSWORD: admin

replicaCount: 1

resources: {}

initContainer:
  enabled: false

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []

nameOverride: ""
fullnameOverride: ""