apiVersion: v2
appVersion: 2.2.0
description: A Helm chart for duplicati
home: https://github.com/L3st86/HelmCharts/tree/master/duplicati
icon: https://raw.githubusercontent.com/L3st86/HelmCharts/master/Duplicati/images/duplicati-logo.png
name: duplicati
sources:
- https://github.com/linuxserver/docker-duplicati
type: application
version: 0.1.0
annotations:
  artifacthub.io/cr.source: "linuxserver/duplicati"
  artifacthub.io/own.source: "linuxserver_duplicati"
  artifacthub.io/cr.update-strategy: "latest"
