apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pageplug.fullname" . }}-storage
  labels:
    {{- include "pageplug.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.app.storage.size }}
  storageClassName: {{ .Values.app.storage.className }}
