apiVersion: v1
kind: Service
metadata:
  name: {{ include "pageplug.fullname" . }}-app
  labels:
    {{- include "pageplug.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pageplug.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app