apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pageplug.fullname" . }}
  labels:
    {{- include "pageplug.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  serviceName: {{ include "pageplug.fullname" . }}-headless
  replicas: 1
  selector:
    matchLabels:
      {{- include "pageplug.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "pageplug.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
      containers:
        - name: app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          volumeMounts:
            - name: storage
              mountPath: /appsmith-stacks
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "pageplug.fullname" . }}-storage
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}