apiVersion: v2
name: autogen-studio
version: 1.0.0
description: A Helm chart for deploying AutoGen Studio
appVersion: "3.10"
annotations:
  artifacthub.io/cr.source: "yuandongtian/autogen"
  artifacthub.io/own.source: "autogen-studio"
  artifacthub.io/cr.update-strategy: "no"