apiVersion: v2
name: changedetection
description: A Helm chart for changedetection.io application
type: application
version: 0.1.0
appVersion: 0.50.38
annotations:
  artifacthub.io/cr.source: "ghcr.io/dgtlmoon/changedetection.io"
  artifacthub.io/own.source: "changedetection"
  artifacthub.io/cr.update-strategy: "latest"