annotations:
  artifacthub.io/cr.source: portainer/portainer-ce
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: portainer-ce
apiVersion: v2
appVersion: 2.33.5
description: A lightweight service delivery platform for containerized applications
name: portainer
type: application
version: 0.1.0
