annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
  artifacthub.io/cr.source: "linuxserver/tautulli"
  artifacthub.io/own.source: "linuxserver_tautulli"
  artifacthub.io/cr.update-strategy: "latest"
apiVersion: v2
appVersion: 2.16.0
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
description: A Python based monitoring and tracking tool for Plex Media Server
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/tautulli
icon: https://github.com/Tautulli/Tautulli/blob/master/data/interfaces/default/images/logo.png?raw=true
keywords:
- tautulli
- plex
kubeVersion: '>=1.16.0-0'
maintainers:
- email: jeff@billimek.com
  name: billimek
name: tautulli
sources:
- https://github.com/Tautulli/Tautulli
- https://github.com/k8s-at-home/container-images
version: 11.4.2
