apiVersion: v2
name: automatisch
version: 1.0.0
description: A Helm chart for Automatisch - Open Source Zapier Alternative
appVersion: 0.15.0
annotations:
  artifacthub.io/cr.source: "automatischio/automatisch"
  artifacthub.io/own.source: "automatischio/automatisch"
  artifacthub.io/cr.update-strategy: "latest"