apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dialoqbase.fullname" . }}-secret
  labels:
    {{- include "dialoqbase.labels" . | nindent 4 }}
type: Opaque
data:
  session-secret: {{ randAlphaNum 32 | b64enc | quote }}
  secret-key: {{ .Values.env.DB_SECRET_KEY | b64enc | quote }}