annotations:
  artifacthub.io/alternativeName: actual
  artifacthub.io/changes: "- kind: changed\n  description: Update actualbudget/actual-server\
    \ image version to 25.8.0\n  links:\n    - name: Upstream Project\n      url:\
    \ https://hub.docker.com/r/actualbudget/actual-server"
  artifacthub.io/containsSecurityUpdates: 'false'
  artifacthub.io/cr.source: actualbudget/actual-server
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/images: "- name: actualbudget\n  image: actualbudget/actual-server:25.8.0\n\
    \  platforms:\n    - linux/amd64\n    - linux/arm64\n    - linux/arm/v7\n"
  artifacthub.io/license: MIT
  artifacthub.io/links: "- name: Chart Source\n  url: https://github.com/community-charts/helm-charts\n\
    - name: Chart Usage Page\n  url: https://community-charts.github.io/docs/charts/actualbudget/usage\n\
    - name: Upstream Project\n  url: https://github.com/actualbudget/actual\n"
  artifacthub.io/maintainers: "- name: burakince\n  email: burak.ince@linux.org.tr\n"
  artifacthub.io/operator: 'false'
  artifacthub.io/own.source: actualbudget_actual-server
  artifacthub.io/prerelease: 'false'
  artifacthub.io/screenshots: "- title: User Interface Overview\n  url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-overview-of-user-interface.png\n\
    - title: Account Register Overview\n  url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-account-register-overview.png\n\
    - title: Budget Overview\n  url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-budget-overview.png\n\
    - title: Payees Overview\n  url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-payees-overview.png\n\
    - title: Reports Overview\n  url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-reports-overview.png\n\
    - title: Rules Overview\n  url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-rules-overview.png\n\
    - title: Schedules Overview\n  url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-schedules-overview.png\n"
  artifacthub.io/signKey: 'fingerprint: 939B1A0ED8AAA8E722ACCDB3B6A012EE8A76426A

    url: https://keybase.io/communitycharts/pgp_keys.asc

    '
apiVersion: v2
appVersion: 25.11.0
description: A local-first personal finance app
home: https://actualbudget.org/
icon: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/actual.png
keywords:
- actualbudget
- actual-budget
- actual
- docker
- finance
- personal-finance
- money
- budgeting
kubeVersion: '>=1.16.0-0'
maintainers:
- email: burak.ince@linux.org.tr
  name: burakince
  url: https://www.burakince.com
name: actualbudget
sources:
- https://github.com/community-charts/helm-charts
- https://github.com/actualbudget/actual
type: application
version: 1.8.1
