annotations:
  artifacthub.io/alternativeName: actual
  artifacthub.io/changes: |-
    - kind: changed
      description: Update actualbudget/actual-server image version to 25.8.0
      links:
        - name: Upstream Project
          url: https://hub.docker.com/r/actualbudget/actual-server
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: actualbudget
      image: actualbudget/actual-server:25.8.0
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/community-charts/helm-charts
    - name: Chart Usage Page
      url: https://community-charts.github.io/docs/charts/actualbudget/usage
    - name: Upstream Project
      url: https://github.com/actualbudget/actual
  artifacthub.io/maintainers: |
    - name: burakince
      email: burak.ince@linux.org.tr
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/screenshots: |
    - title: User Interface Overview
      url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-overview-of-user-interface.png
    - title: Account Register Overview
      url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-account-register-overview.png
    - title: Budget Overview
      url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-budget-overview.png
    - title: Payees Overview
      url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-payees-overview.png
    - title: Reports Overview
      url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-reports-overview.png
    - title: Rules Overview
      url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-rules-overview.png
    - title: Schedules Overview
      url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-schedules-overview.png
  artifacthub.io/signKey: |
    fingerprint: 939B1A0ED8AAA8E722ACCDB3B6A012EE8A76426A
    url: https://keybase.io/communitycharts/pgp_keys.asc
  artifacthub.io/cr.source: "actualbudget/actual-server"
  artifacthub.io/own.source: "actualbudget_actual-server"
  artifacthub.io/cr.update-strategy: "force-numer"
apiVersion: v2
appVersion: 25.9.0
description: A local-first personal finance app
home: https://actualbudget.org/
icon: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/actual.png
keywords:
- actualbudget
- actual-budget
- actual
- docker
- finance
- personal-finance
- money
- budgeting
kubeVersion: '>=1.16.0-0'
maintainers:
- email: burak.ince@linux.org.tr
  name: burakince
  url: https://www.burakince.com
name: actualbudget
sources:
- https://github.com/community-charts/helm-charts
- https://github.com/actualbudget/actual
type: application
version: 1.8.1