annotations:
  artifacthub.io/cr.source: evershop/evershop
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: evershop_evershop
apiVersion: v2
appVersion: 2.1.0
name: evershop
version: 0.1.0
