## Main application configuration
app:
  image:
    repository: evershop/evershop
    tag:
    pullPolicy: IfNotPresent
  port: 3000
  replicaCount: 1
  env:
    DB_PORT: 5432
    DB_NAME: postgres
    DB_USER: postgres
  secrets:
    DB_PASSWORD: postgres

## PostgreSQL configuration
postgresql:
  enabled: true
  image:
    repository: postgresql.image
    tag: postgresql.image.tag
    pullPolicy: IfNotPresent
  port: 5432
  user: postgres
  password: postgres
  db: postgres
  persistence:
    enabled: true
    storageClassName: ""
    size: 20Gi

## Global configuration
replicaCount: 1