{{- if .Values.services.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    io.kompose.service: redis-service
  name: redis-service
spec:
  serviceName: redis-service
  replicas: {{ .Values.services.redis.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: redis-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: redis-service
    spec:
      initContainers:
      - name: init-redis-permissions
        image: {{ .Values.image.busybox }}
        command: ['sh', '-c', 'chown -R 1001:1001 /data && chmod -R 777 /data']
        volumeMounts:
        - name: redis-data
          mountPath: /data
      securityContext:
        fsGroup: 1001
      containers:
      - args:
        - redis-server 
        - --requirepass 
        - {{ .Values.services.redis.password }}
        - --dir
        - /data
        - --dbfilename
        - dump.rdb
        image: {{ .Values.services.redis.image }}
        imagePullPolicy: ""
        name: redis-service
        ports:
        - containerPort: {{ .Values.services.redis.port }}
        {{ with .Values.services.redis.resources }}
        resources:
        {{- toYaml . | nindent 10 }}
        {{ end }}
        volumeMounts:
        - mountPath: /data
          name: redis-data
        {{ if .Values.services.redis.extraVolumeMounts }}
          {{- toYaml .Values.services.redis.extraVolumeMounts | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
    {{- if .Values.services.redis.extraContainers }}
      {{- toYaml .Values.services.redis.extraContainers | nindent 6 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{ if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{ end }}
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      {{ end }}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data
      {{ if .Values.services.redis.extraVolumes }}
        {{- toYaml .Values.services.redis.extraVolumes | nindent 6 }}
      {{- end }}

status: {}
{{- end }}
