{{- if eq .Values.service.type "LoadBalancer" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "bookstack.fullname" . }}-ip-updater"
  labels:
    app: {{ template "bookstack.name" . }}
    release: {{ .Release.Name }}
{{- end }}