apiVersion: v1
kind: Service
metadata:
  name: {{ include "twenty.fullname" . }}-db
  labels:
    {{- include "twenty.labels" . | nindent 4 }}
    app: {{ include "twenty.name" . }}-db
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
      protocol: TCP
      name: postgresql
  selector:
    {{- include "twenty.selectorLabels" . | nindent 4 }}
    app: {{ include "twenty.name" . }}-db