{{- if eq .Values.server.service.type "LoadBalancer" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "twenty.fullname" . }}-ip-updater-role"
  labels:
    {{- include "twenty.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "patch"]
{{- end }}