{{- if eq .Values.server.service.type "LoadBalancer" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "twenty.fullname" . }}-ip-updater"
  labels:
    {{- include "twenty.labels" . | nindent 4 }}
{{- end }}