apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cockpit.fullname" . }}-pvc
  labels:
    {{- include "cockpit.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}