# Default values for pageplug.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global Docker image parameters
# Please, note that this will override the image parameters, including dependencies, configured to use the global value
# Current available global Docker image parameters: imageRegistry and imagePullSecrets
imageRegistry: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# application configuration
app:
  image:
    repository: registry.cn-beijing.aliyuncs.com/cloudtogo-offical/pageplug-ce
    tag: v1.9.39
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
  storage:
    size: 20Gi
    className: alicloud-disk-topology-alltype
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

persistence:
  enabled: true
  ## pageplug data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  # existingClaim: ""
  accessMode: ReadWriteOnce
  size: 20Gi