annotations:
  artifacthub.io/changes: "- kind: changed\n  description: Bump tag to version-v5.2.5\n"
  artifacthub.io/cr.source: linuxserver/mstream
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/images: "- name: mstream\n  image: linuxserver/mstream:5.13.1\n"
  artifacthub.io/own.source: linuxserver_mstream
apiVersion: v2
appVersion: v5.13.1-ls213
dependencies:
- name: common
  repository: https://nicholaswilde.github.io/helm-charts/
  version: ~0.1.13
description: A personal music streaming server
home: https://github.com/nicholaswilde/helm-charts/tree/main/charts/mstream
icon: https://raw.githubusercontent.com/nicholaswilde/helm-charts/main/images/mstream.png
keywords:
- mstream
- server
- music
maintainers:
- email: ncwilde43@gmail.com
  name: nicholaswilde
name: mstream
sources:
- https://github.com/linuxserver/docker-mstream
- https://mstream.io/
type: application
version: 2.1.2
