apiVersion: v2
appVersion: 2.3.1
description: Flame is self-hosted startpage for your server. Easily manage your apps
  and bookmarks with built-in editors.
name: flame
type: application
version: 0.3.0
annotations:
  artifacthub.io/cr.source: "pawelmalak/flame"
  artifacthub.io/own.source: "pawelmalak_flame"
  artifacthub.io/cr.update-strategy: "latest"