annotations:
  artifacthub.io/cr.source: ghcr.io/666ghj/bettafish
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: bettafish
apiVersion: v2
appVersion: 2.0.0
description: A Helm chart for BettaFish 舆情分析系统.
name: bettafish
type: application
version: 0.1.0
