apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mutimodal-agent.fullname" . }}-config
  labels:
    {{- include "mutimodal-agent.labels" . | nindent 4 }}
data:
  config.toml: |
    [server]
    port = 8501
    address = "0.0.0.0"
    maxUploadSize = 200
    enableCORS = true
    enableXsrfProtection = false
    headless = true
    runOnSave = true
    browser.gatherUsageStats = false
    client.displayTracking = false
    enableWebsocketCompression = false
    allowRunOnSave = true
    
    [browser]
    gatherUsageStats = false
    
    [client]
    displayTracking = false
    toolbarMode = "minimal"