apiVersion: v1
kind: Service
metadata:
  name: {{ include "mutimodal-agent.fullname" . }}
  labels:
    {{- include "mutimodal-agent.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mutimodal-agent.selectorLabels" . | nindent 4 }}