annotations:
  artifacthub.io/cr.source: gotenberg/gotenberg
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/links: "- name: Projects Homepage\n  url: https://gotenberg.dev/\n\
    - name: Projects GitHub\n  url: https://github.com/gotenberg/gotenberg\n- name:\
    \ Chart's GitHub\n  url: https://github.com/MaikuMori/helm-charts/tree/master/charts/gotenberg\n\
    - name: Chart's Changelog\n  url: https://github.com/MaikuMori/helm-charts/blob/master/charts/gotenberg/CHANGELOG.md\n"
  artifacthub.io/own.source: gotenberg_gotenberg
apiVersion: v2
appVersion: 8.25.0
description: A Helm chart for Gotenberg
icon: https://user-images.githubusercontent.com/8983173/130322857-185831e2-f041-46eb-a17f-0a69d066c4e5.png
keywords:
- gotenberg
- pdf
maintainers:
- email: mikskalnins@maikumori.com
  name: MaikuMori
  url: maikumori.com
name: gotenberg
sources:
- https://github.com/gotenberg/gotenberg
- https://github.com/MaikuMori/helm-charts/tree/master/charts/gotenberg
type: application
version: 1.12.0
