apiVersion: v1
kind: Service
metadata:
  name: {{ include "trendradar.fullname" . }}-file-server
  labels:
    {{- include "trendradar.labels" . | nindent 4 }}
    app: file-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "trendradar.selectorLabels" . | nindent 4 }}
    app: file-server