annotations:
  artifacthub.io/complex: 'true'
  artifacthub.io/cr.source: budibase/apps
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: budibase/apps
  artifacthub.io/source: "[\n  {\n    \"own.source\": \"budibase/apps\",\n    \"cr.source\"\
    : \"budibase/apps\"\n  },\n  {\n    \"own.source\": \"budibase/proxy\",\n    \"\
    cr.source\": \"budibase/proxy\"\n  },\n  {\n    \"own.source\": \"budibase/worker\"\
    ,\n    \"cr.source\": \"budibase/worker\"\n  }\n]\n"
apiVersion: v2
appVersion: 3.23.15
dependencies:
- condition: services.couchdb.enabled
  name: couchdb
  repository: https://apache.github.io/couchdb-helm
  version: 4.5.6
description: Budibase is an open source low-code platform, helping thousands of teams
  build apps for their workplace in minutes.
keywords:
- low-code
- database
- cluster
name: budibase
sources:
- https://github.com/Budibase/budibase
- https://budibase.com
type: application
version: 3.0.472
