apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "beifong.fullname" . }}-post-deploy-hook
  labels:
    {{- include "beifong.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}