apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "beifong.fullname" . }}-post-deploy-hook
  labels:
    {{- include "beifong.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "beifong.fullname" . }}-post-deploy-hook
subjects:
- kind: ServiceAccount
  name: {{ include "beifong.fullname" . }}-post-deploy-hook
  namespace: {{ .Release.Namespace }}