apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "beifong.fullname" . }}-post-deploy-hook
  labels:
    {{- include "beifong.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "update"]