apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valuecell.fullname" . }}
  labels:
    {{- include "valuecell.labels" . | nindent 4 }}
data:
  .env: |
    APP_NAME={{ .Values.app.name }}
    APP_VERSION={{ .Values.app.version }}
    APP_ENVIRONMENT={{ .Values.app.environment }}
    API_DEBUG={{ .Values.app.debug }}
    API_ENABLED={{ .Values.api.enabled }}
    API_HOST={{ .Values.api.host }}
    API_PORT={{ .Values.api.port }}
    LANG={{ .Values.app.language }}
    TIMEZONE={{ .Values.app.timezone }}