apiVersion: v2
appVersion: 2.1.9-rc.1
dependencies:
- name: higress-core
  repository: file://../core
  version: 2.1.9-rc.1
- name: higress-console
  repository: https://higress.io/helm-charts/
  version: 2.1.8
description: Helm chart for deploying Higress gateways
home: http://higress.io/
icon: https://higress.io/img/higress_logo_small.png
keywords:
- higress
- gateways
name: higress
sources:
- http://github.com/alibaba/higress
type: application
version: 2.1.9-rc.1
annotations:
  artifacthub.io/cr.source: "higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/higress"
  artifacthub.io/own.source: "higress"
  artifacthub.io/cr.update-strategy: "no"
