annotations:
  artifacthub.io/cr.source: twentycrm/twenty
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: twenty
apiVersion: v2
appVersion: v1.12.0
description: A Helm chart for Twenty CRM
name: twenty
type: application
version: 0.1.0
