annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump tag to version-1.7.18
  artifacthub.io/images: |
    - name: grav
      image: ghcr.io/linuxserver/grav:version-1.7.18
  artifacthub.io/cr.source: "linuxserver/grav"
  artifacthub.io/own.source: "linuxserver_grav"
  artifacthub.io/cr.update-strategy: "latest"
apiVersion: v2
appVersion: 1.7.50
dependencies:
- name: common
  repository: https://nicholaswilde.github.io/helm-charts/
  version: ~0.1.13
description: A Fast, Simple, and Flexible, file-based Web-platform.
home: https://github.com/nicholaswilde/helm-charts/tree/main/charts/grav
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/grav-logo.png
keywords:
- grav
- web
- platform
- file
maintainers:
- email: ncwilde43@gmail.com
  name: nicholaswilde
name: grav
sources:
- https://github.com/linuxserver/docker-grav
- https://github.com/getgrav/grav/
type: application
version: 0.1.6
