replicaCount: 1
image:
  repository: lakhansamani/authorizer
  tag:
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 8080
env:
  ENV: production
  DATABASE_TYPE: sqlite
  DATABASE_URL: data.db
  CUSTOM_ACCESS_TOKEN_SCRIPT: "function(user,tokenPayload){var data = tokenPayload;data.extra = {'x-extra-id': user.id};return data;}"
  DISABLE_PLAYGROUND: true
postgresql:
  enabled: postgresql.enabled
  image: postgresql.image
  postgresqlUsername: postgresql.username
  postgresqlPassword: postgresql.password
  postgresqlDatabase: authorizer
  persistence:
    enabled: persistence.enabled
    storageClassName: ""
    size: 20Gi
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}