{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-financial-coach-chart.fullname" . }}-secrets
  labels:
    {{- include "ai-financial-coach-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.externalEnv.app.googleApiKey }}
  GOOGLE_API_KEY: {{ .Values.externalEnv.app.googleApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
