apiVersion: v2
name: valuecell
description: A Helm chart for ValueCell - a community-driven, multi-agents platform for financial applications
type: application
version: 0.1.0
appVersion: latest
annotations:
  artifacthub.io/cr.source: "tntest/valuecell"
  artifacthub.io/own.source: "valuecell"
  artifacthub.io/cr.update-strategy: "no"