apiVersion: v2
name: answer
version: 1.0.0
description: Helm chart for deploying Apache Answer
appVersion: 1.6.0
annotations:
  artifacthub.io/cr.source: "apache/answer"
  artifacthub.io/own.source: "answer"
  artifacthub.io/cr.update-strategy: "latest"