image:
  repository: apache/answer
  tag:
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 9080
  targetPort: 80

ingress:
  enabled: false
  hosts:
    - host: answer.local
      paths:
        - /
  tls: []

resources:
  {}

nodeSelector: {}

tolerations: []

affinity: {}

volumes:
  - name: answer-data
    persistentVolumeClaim:
      claimName: answer-pvc

persistent:
  enabled: true
  storageClassName: cloudapp.storageClassName
  storage: cloudapp.storageClass
