{{- if or .Values.externalEnv.app.password  }}
{{- if not .Values.flame.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "flame.labels" . | nindent 4 }}
data:
  password: {{ .Values.externalEnv.app.password | b64enc | quote }}
{{- end }}
{{- end }}