replicaCount: 1
image:
  repository: caronc/apprise
  tag:
  pullPolicy: IfNotPresent
env:
  APPRISE_STATEFUL_MODE: simple
  APPRISE_CONFIG_DIR: /config
  APPRISE_ATTACH_DIR: /attach
  APPRISE_PLUGIN_PATHS: /plugin
ports:
  containerPort: 8000
resources:
  {}
persistence:
  storageClassName: ""
  config:
    size: 20Gi
  attach:
    size: 20Gi
  plugin:
    size: 20Gi
service:
  type: LoadBalancer
  port: 8000
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: apprise-api.local
      paths: []