apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    {{- include "coral-talk.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.mongodb.containerPort }}
      targetPort: {{ .Values.mongodb.containerPort }}
      protocol: TCP
  selector:
    app: mongodb