apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "coral-talk.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.redis.containerPort }}
      targetPort: {{ .Values.redis.containerPort }}
      protocol: TCP
  selector:
    app: redis