annotations:
  artifacthub.io/changes: |
    - kind: added
      description: values.schema.json
    - kind: changed
      description: Bump common to 0.1.13
    - kind: changed
      description: Bump mariadb to 1.0.5
    - kind: changed
      description: Change tag to version-v1.5.0 in order to reduce the number of chart updates.
  artifacthub.io/images: |
    - name: shiori
      image: ghcr.io/nicholaswilde/shiori:version-v1.5.0
  artifacthub.io/cr.source: "nicholaswilde/shiori"
  artifacthub.io/own.source: "nicholaswilde_shiori"
  artifacthub.io/cr.update-strategy: "latest"
apiVersion: v2
appVersion: v1.5.0-ls3
dependencies:
- name: common
  repository: https://nicholaswilde.github.io/helm-charts/
  version: ~0.1.13
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  tags:
  - postgres
  version: 12.5.6
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 19.1.x
description: A simple bookmark manager built with Go
home: https://github.com/nicholaswilde/helm-charts/tree/main/charts/shiori
icon: https://github.com/go-shiori/shiori/raw/master/internal/view/res/apple-touch-icon-152x152.png
keywords:
- shiori
- bookmark
- bookmark-manager
- web-interface
maintainers:
- email: ncwilde43@gmail.com
  name: nicholaswilde
name: shiori
sources:
- https://github.com/go-shiori/shiori
- https://github.com/nicholaswilde/docker-shiori
type: application
version: 1.0.1
