annotations:
  artifacthub.io/cr.source: opencoze/opencoze
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: opencoze
apiVersion: v2
appVersion: 0.3.11
description: opencoze is a ai agent platform.
name: coze
type: application
version: 0.0.1
