annotations:
  artifacthub.io/cr.source: deluan/navidrome
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: deluan_navidrome
apiVersion: v2
appVersion: 0.58.5
description: Experimental helm chart to run navidrome
name: navidrome
type: application
version: 0.2.5
