replicaCount: 1

image:
  repository: etherpad/etherpad
  pullPolicy: IfNotPresent
  tag:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 5001

securityContext:
  runAsNonRoot: true
  runAsUser: 5001

service:
  type: LoadBalancer
  port: 9001
  targetPort: 9001

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

etherpad:
  adminPassword: "admin"
  trustProxy: "true"
  disableIpLogging: "false"
  defaultPadText: " "

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: postgres
    tag: "15-alpine"
  auth:
    username: admin
    password: admin
    database: etherpad
    port: 5432
  primary:
    persistence:
      enabled: true
      storageClass: "alicloud-disk-essd"
      accessModes:
        - ReadWriteOnce
      size: 20Gi
  resources: {}
persistence:
  plugins:
    enabled: true
    storageClass: "alicloud-disk-essd"
    accessModes:
      - ReadWriteOnce
    size: 20Gi
  var:
    enabled: true
    storageClass: "alicloud-disk-essd"
    accessModes:
      - ReadWriteOnce
    size: 20Gi
