apiVersion: v2
appVersion: 2.12.0
description: Restreamer helm chart
name: restreamer
type: application
version: 1.1.0
annotations:
  artifacthub.io/cr.source: "datarhei/restreamer"
  artifacthub.io/own.source: "datarhei_restreamer"
  artifacthub.io/github.source: "https://api.github.com/repos/datarhei/restreamer/releases/latest"
  artifacthub.io/cr.update-strategy: "github"