apiVersion: v2
appVersion: 1.5.0
annotations:
  artifacthub.io/cr.source: "stirlingtools/stirling-pdf"
  artifacthub.io/own.source: "stirlingtools_stirling-pdf"
  artifacthub.io/cr.update-strategy: "latest"
description: locally hosted web application that allows you to perform various operations
  on PDF files
home: https://github.com/Stirling-Tools/Stirling-PDF
keywords:
- stirling-pdf
- helm
- charts repo
maintainers:
- name: Stirling-Tools
  url: https://github.com/Stirling-Tools/Stirling-PDF-chart
name: stirling-pdf-chart
sources:
- https://github.com/Stirling-Tools/Stirling-PDF-chart
version: 2.1.0
