annotations:
  artifacthub.io/cr.source: neosmemo/memos
  artifacthub.io/cr.update-strategy: github
  artifacthub.io/github.source: https://api.github.com/repos/usememos/memos/releases/latest
  artifacthub.io/own.source: neosmemo_memos
apiVersion: v2
appVersion: 0.25.3
description: A Helm chart for Memos - A modern, open-source, self-hosted knowledge
  management and note-taking platform
name: memos
type: application
version: 0.1.0
