annotations:
  artifacthub.io/cr.source: cherrystudio/cherry-studio-enterprise-api
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: cherry-studio-enterprise-api
apiVersion: v2
appVersion: v0.3.0
description: A Helm chart for Cherry Studio Enterprise
name: cherry-studio-enterprise
type: application
version: 1.0.4
