apiVersion: v2
name: bytestash
description: A Helm chart for deploying ByteStash to Kubernetes
type: application
version: 0.1.1
appVersion: 1.5.7
annotations:
  artifacthub.io/cr.source: "ghcr.io/jordan-dalby/bytestash"
  artifacthub.io/own.source: "bytestash"
  artifacthub.io/cr.update-strategy: "latest"