annotations:
  artifacthub.io/cr.source: ghcr.io/jordan-dalby/bytestash
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: bytestash
apiVersion: v2
appVersion: 1.5.9
description: A Helm chart for deploying ByteStash to Kubernetes
name: bytestash
type: application
version: 0.1.1
