{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "farfalle.fullname" . }}-db
  labels:
    {{- include "farfalle.labels" . | nindent 4 }}
    app: db
spec:
  serviceName: {{ include "farfalle.fullname" . }}-db
  replicas: 1
  selector:
    matchLabels:
      {{- include "farfalle.selectorLabels" . | nindent 6 }}
      app: db
  template:
    metadata:
      labels:
        {{- include "farfalle.selectorLabels" . | nindent 8 }}
        app: db
    spec:
      containers:
        - name: db
          image: "{{ .Values.database.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: db
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.database.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.database.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.database.name }}"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
              subPath: postgresql
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: {{ include "farfalle.fullname" . }}-db-pvc
{{- end }}