{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "farfalle.fullname" . }}-db
  labels:
    {{- include "farfalle.labels" . | nindent 4 }}
    app: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: db
  selector:
    {{- include "farfalle.selectorLabels" . | nindent 4 }}
    app: db
{{- end }}