apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "farfalle.fullname" . }}-searxng
  labels:
    {{- include "farfalle.labels" . | nindent 4 }}
    app: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "farfalle.selectorLabels" . | nindent 6 }}
      app: searxng
  template:
    metadata:
      labels:
        {{- include "farfalle.selectorLabels" . | nindent 8 }}
        app: searxng
    spec:
      containers:
        - name: searxng
          image: "{{ .Values.searxng.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: searxng
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi