apiVersion: v1
kind: Service
metadata:
  name: {{ include "farfalle.fullname" . }}-searxng
  labels:
    {{- include "farfalle.labels" . | nindent 4 }}
    app: searxng
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: searxng
  selector:
    {{- include "farfalle.selectorLabels" . | nindent 4 }}
    app: searxng