{{- if eq .Values.service.type "LoadBalancer" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "farfalle.fullname" . }}-ip-updater"
  labels:
    {{- include "farfalle.labels" . | nindent 4 }}
{{- end }}