apiVersion: v1
kind: Service
metadata:
  name: {{ include "farfalle.fullname" . }}-standalone
  labels:
    {{- include "farfalle.labels" . | nindent 4 }}
    app: standalone
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.standalone.backendPort }}
      targetPort: {{ .Values.standalone.backendPort }}
      protocol: TCP
      name: backend
    - port: {{ .Values.standalone.frontendPort }}
      targetPort: {{ .Values.standalone.frontendPort }}
      protocol: TCP
      name: frontend
  selector:
    {{- include "farfalle.selectorLabels" . | nindent 4 }}
    app: standalone