apiVersion: v1
kind: Service
metadata:
  name: {{ include "cordys-crm.fullname" . }}
  labels:
    {{- include "cordys-crm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cordys.service.type }}
  ports:
    - port: {{ .Values.cordys.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
    - port: {{ .Values.cordys.service.mcpPort }}
      targetPort: 8082
      protocol: TCP
      name: mcp
  selector:
    {{- include "cordys-crm.selectorLabels" . | nindent 4 }}