annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update ghcr.io/miniflux/miniflux docker tag to v2.2.14
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/miniflux/v2
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/miniflux
  artifacthub.io/cr.source: "miniflux/miniflux"
  artifacthub.io/own.source: "miniflux_miniflux"
  artifacthub.io/cr.update-strategy: "latest"
apiVersion: v2
appVersion: 2.2.14
dependencies:
- name: common
  repository: https://bjw-s.github.io/helm-charts
  version: 1.5.1
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 14.0.5
description: Miniflux is a minimalist and opinionated feed reader.
home: https://charts.gabe565.com/charts/miniflux/
icon: https://raw.githubusercontent.com/miniflux/logo/40cb83c/icon.svg
keywords:
- miniflux
- rss
- news
- feed
kubeVersion: '>=1.22.0-0'
name: miniflux
sources:
- https://github.com/miniflux/v2
type: application
version: 0.9.2
