annotations:
  artifacthub.io/cr.source: filebrowser/filebrowser
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: filebrowser
apiVersion: v2
appVersion: v2.48.2
description: A Helm chart for File Browser - Web File Manager
name: filebrowser
type: application
version: 0.1.0
