apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thumbor.fullname" . }}-secret
  labels:
    {{- include "thumbor.labels" . | nindent 4 }}
type: Opaque
data:
  securityKey: {{ .Values.thumbor.securityKey | b64enc | quote }}