apiVersion: v2
appVersion: 0.71.0
description: Activepieces is an open-source business automation tool
icon: https://cdn.activepieces.com/pieces/activepieces.png
name: activepieces
type: application
version: 0.1.6
annotations:
  # 自定义 Annotation，用于存放镜像的原始出处
  artifacthub.io/cr.source: "docker.io/actualbudget/actual-server"
  artifacthub.io/own.source: "activepieces"
  artifacthub.io/github.source: "https://api.github.com/repos/activepieces/activepieces/releases/latest"
  artifacthub.io/cr.update-strategy: "github"