annotations:
  artifacthub.io/cr.source: activepieces/activepieces
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: activepieces
apiVersion: v2
appVersion: 0.71.4
description: Activepieces is an open-source business automation tool
icon: https://cdn.activepieces.com/pieces/activepieces.png
name: activepieces
type: application
version: 0.1.6
