{{- if eq .Values.frontend.service.type "LoadBalancer" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "agentgpt.fullname" . }}-ip-updater"
  labels:
    {{- include "agentgpt.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- end }}