{{- if eq .Values.frontend.service.type "LoadBalancer" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "agentgpt.fullname" . }}-ip-updater"
  labels:
    {{- include "agentgpt.labels" . | nindent 4 }}
{{- end }}