{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentgpt.fullname" . }}-mysql
  labels:
    {{- include "agentgpt.labels" . | nindent 4 }}
    app: mysql
spec:
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    {{- include "agentgpt.selectorLabels" . | nindent 4 }}
    app: mysql
{{- end }}