apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentgpt.fullname" . }}-mysql
  labels:
    {{- include "agentgpt.labels" . | nindent 4 }}
    app: mysql
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
  mysql-user: {{ .Values.mysql.user | b64enc | quote }}
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}
  mysql-database: {{ .Values.mysql.database | b64enc | quote }}