{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agentgpt.fullname" . }}-mysql
  labels:
    {{- include "agentgpt.labels" . | nindent 4 }}
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "agentgpt.selectorLabels" . | nindent 6 }}
      app: mysql
  template:
    metadata:
      labels:
        {{- include "agentgpt.selectorLabels" . | nindent 8 }}
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.imagePullPolicy }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
        {{- if .Values.mysql.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "agentgpt.fullname" . }}-mysql-pvc
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- end }}