{{- if and .Values.mysql.enabled .Values.mysql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agentgpt.fullname" . }}-mysql-pvc
  labels:
    {{- include "agentgpt.labels" . | nindent 4 }}
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size | quote }}
{{- end }}