{{- if and .Values.externalEnv.postgresql.enabled .Values.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cherry-studio-enterprise.fullname" . }}-postgresql-data
  labels:
    {{- include "cherry-studio-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode | quote }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | quote }}
{{- end }}