{{- if .Values.externalEnv.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cherry-studio-enterprise.fullname" . }}-postgresql
  labels:
    {{- include "cherry-studio-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  postgres-password: {{ .Values.externalEnv.postgresql.env.DB_PASSWORD | b64enc | quote }}
{{- end }}