{{- if .Values.externalEnv.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cherry-studio-enterprise.fullname" . }}-postgresql
  labels:
    {{- include "cherry-studio-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    {{- include "cherry-studio-enterprise.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}