annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: '>=1.24'
  artifacthub.io/cr.source: "flowiseai/flowise"
  artifacthub.io/own.source: "flowiseai_flowise"
  artifacthub.io/github.source: "https://api.github.com/repos/flowiseai/flowise/releases/latest"
  artifacthub.io/cr.update-strategy: "github"
apiVersion: v2
appVersion: 3.0.8
dependencies:
- name: common
  repository: oci://ghcr.io/cowboysysop/charts
  version: 2.31.3
- condition: mariadb.enabled
  name: mariadb
  repository: oci://ghcr.io/cowboysysop/charts
  version: 20.4.2
- condition: postgresql.enabled
  name: postgresql
  repository: oci://ghcr.io/cowboysysop/charts
  version: 15.5.7
- condition: redis.enabled
  name: redis
  repository: oci://ghcr.io/cowboysysop/charts
  version: 21.2.6
description: Drag & drop UI to build your customized LLM flow
home: https://flowiseai.com/
icon: https://avatars.githubusercontent.com/u/128289781
maintainers:
- email: sebastien.prudhomme@gmail.com
  name: sebastien-prudhomme
name: flowise
sources:
- https://github.com/FlowiseAI/Flowise
- https://github.com/cowboysysop/charts/tree/master/charts/flowise
version: 6.0.0
