apiVersion: v2
appVersion: v2.16.0
description: A Helm chart for Kubernetes
name: chatgpt-next-web
type: application
version: 0.1.1
annotations:
  artifacthub.io/cr.source: "yidadaa/chatgpt-next-web"
  artifacthub.io/own.source: "yidadaa_chatgpt-next-web"
  artifacthub.io/cr.update-strategy: "latest"
